Ios 18
MiletaA/Receipt-Wallet pull request #14
Opened 2023-12-11 15:15 UTC by dekeract10

Corrected bugs which were detected in testing.

2023-12-11 15:18 UTC, MilePrastalo commented on Receipt Wallet/CreateWarrantyView.swift
> +        nameInputLabel.accessibilityIdentifier = "nameInputLabel"
accessibility identifier should set at view definition inside lazy var...

2023-12-11 15:20 UTC, MilePrastalo commented on Receipt Wallet/SelectCategoryView.swift
> +        NSLayoutConstraint.activate([
stick to one format for setting constraints

2023-12-11 15:20 UTC, MilePrastalo commented on Receipt Wallet/SelectCategoryViewController.swift
> +        selectCategoryView.buttons.forEach{button in
adding target and filtering should be moved to viewDidLoad

2023-12-11 15:21 UTC, MilePrastalo requested changes
see comments

2023-12-12 09:17 UTC, mknzvc approved these changes

2023-12-12 09:20 UTC, MilePrastalo approved these changes

2023-12-12 09:20 UTC, merged